version: 2
registries:
  docker-registry-quay-io:
    type: docker-registry
    url: https://quay.io
    username: sdase+dependabot
    password: "${{secrets.DOCKER_REGISTRY_QUAY_IO_PASSWORD}}"
  npm-registry-npm-intern-sda-se-online:
    type: npm-registry
    url: https://npm.intern.sda-se.online/
    token: "${{secrets.NPM_REGISTRY_NPM_INTERN_SDA_SE_ONLINE_TOKEN}}"

updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 33
  target-branch: dev
  ignore:
  - dependency-name: google-auth
    versions:
    - 1.24.0
    - 1.25.0
    - 1.26.0
    - 1.26.1
    - 1.27.0
    - 1.27.1
    - 1.28.0
    - 1.28.1
    - 1.29.0
  - dependency-name: google-api-python-client
    versions:
    - 1.12.8
    - 2.0.0
    - 2.0.1
    - 2.0.2
    - 2.1.0
    - 2.2.0
  - dependency-name: humanize
    versions:
    - 3.2.0
    - 3.3.0
    - 3.4.0
  - dependency-name: django-extensions
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.1.post1
    - 3.1.2
  - dependency-name: pillow
    versions:
    - 8.1.0
    - 8.1.1
    - 8.1.2
  - dependency-name: google-auth-oauthlib
    versions:
    - 0.4.2
    - 0.4.3
  - dependency-name: django-crispy-forms
    versions:
    - 1.10.0
    - 1.11.0
    - 1.11.1
  - dependency-name: django
    versions:
    - 3.1.5
    - 3.1.6
    - 3.1.7
  - dependency-name: asteval
    versions:
    - 0.9.21
    - 0.9.22
  - dependency-name: urllib3
    versions:
    - 1.26.3
  - dependency-name: coverage
    versions:
    - "5.4"
  - dependency-name: mysql-connector-python
    versions:
    - 8.0.23
  - dependency-name: pytz
    versions:
    - "2020.5"
  - dependency-name: pygithub
    versions:
    - 1.54.1
  - dependency-name: lxml
    versions:
    - 4.6.2
  - dependency-name: django-slack
    versions:
    - 5.16.0
  - dependency-name: djangorestframework
    versions:
    - 3.12.2
  - dependency-name: markdown
    versions:
    - 3.3.3
  - dependency-name: supervisor
    versions:
    - 4.2.1
- package-ecosystem: npm
  directory: "/components"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 33
  target-branch: dev
  ignore:
  - dependency-name: clipboard
    versions:
    - 2.0.7
  - dependency-name: justgage
    versions:
    - 1.4.0
    - 1.4.1
  - dependency-name: fullcalendar
    versions:
    - 5.5.1
  - dependency-name: easymde
    versions:
    - 2.13.0
  - dependency-name: startbootstrap-sb-admin-2
    versions:
    - 4.1.3
  - dependency-name: flot
    versions:
    - 4.2.1
  registries:
  - npm-registry-npm-intern-sda-se-online
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    day: wednesday
    time: "02:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 33
  target-branch: dev
  ignore:
  - dependency-name: nginx
    versions:
    - 1.19.6
    - 1.19.7
    - 1.19.8
    - 1.19.9
  - dependency-name: python
    versions:
    - 3.9.1.pre.slim.pre.buster
    - 3.9.2.pre.slim.pre.buster
  registries:
  - docker-registry-quay-io
