dependencies:
  - name: postgresql
    version: 9.8.11
    repository: "@bitnami"
    condition: postgresql.enabled
  - name: rabbitmq
    version: 8.0.2
    repository: "@bitnami"
    condition: rabbitmq.enabled
  - name: redis
    version: 12.0.0
    repository: "@bitnami"
    condition: redis.enabled
